### ISSUE TITLE
Bug: The logo in the footer is outdated

### ISSUE THREAD

**Issue by Lakszy** [wix/wix-appointments-subscriptions-nextjs-template#256]
**To produce**: Just navigate to the footer section

![image](https://github.com/wix/wix-appointments-subscriptions-nextjs-template/assets/117038630/74a47763-a301-4730-a791-4b43ab9df443)

The logo should be according to the latest **Twitter** guidelines.

@Lakszy

**Comment by carmelc** [comment]
https://github.com/wix/wix-appointments-subscriptions-nextjs-template/pull/452 done, thanks for letting us know
